### ISSUE TITLE
VM needs to be set up

### ISSUE THREAD

**Issue by illepic** [illepic/downfall-guild#1]
Using Drupal VM, preferrably PHP7.

**Comment by ckoppenhaver** [comment]
You could use hiphopVM.
https://github.com/facebook/hhvm

**Comment by Grasen** [comment]
While your at it i need the starter taken off this truck

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 7, 2015 at 12:17 PM, Courtney Koppenhaver<notifications@github.com> wrote:   
You could use hiphopVM.
https://github.com/facebook/hhvm

**Comment by illepic** [comment]
Well, look who gets emails form this repo still!! (Grasen learn some goddamn code so you can contribute here)

**Comment by Grasen** [comment]
To busy fixing trucks 

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 7, 2015 at 3:43 PM, Christopher Bloom<notifications@github.com> wrote:   
Well, look who gets emails form this repo still!! (Grasen learn some goddamn code so you can contribute here)

**Comment by illepic** [comment]
VM is solid using the Drupal VM project (https://github.com/geerlingguy/drupal-vm) and our custom config.yml and drupal composer file.
