### ISSUE TITLE
Discuss: should all new content types (Image, Event, Guide, Post) be consolidated to just Post?

### ISSUE THREAD

**Issue by illepic** [illepic/downfall-guild#37]
With some clever field grouping, we could technically just have one content type - Post - that holds all this info.

## Pros

- simpler migration
- less redundancy of fields 
- easier for developers

## Cons

- much less flexibility
- no clear indication of type of content in all default admin views
- more complexity for users creating content
- harder to link to "create event|image|guide" with the proper fields exposed/fields prefilled
- Would require enabling Signup for everything

**Comment by illepic** [comment]
@saedo

**Comment by saedo** [comment]
what if the subject is force filled too?   like if they want to create event.   check sign up option.   date and raid fields appear.   on submit, regardless of what they do, we have the auto tag "event"  and auto append their subject like with prefix "Event:". 

could do same with Guide. 

Post and Image don't apply. 

Though for Image, it can all auto associate with one of the Galleries,  so we can sort those out. 

That just leaves Post being anything not in a Gallery, nor have Event nor Guide associated with it.

**Comment by illepic** [comment]
@saedo, you're suggesting essentially that Event is rolled into Post. So our content types would be:

- Post - now includes start/end date fields
- Image (actually I'm changing this to Media as it will let us post both image and video)
- Guide

**Comment by illepic** [comment]
Actually, now that I think about it: Events will need signup functionality, something I don't want to have junking up Posts.

**Comment by Grasen** [comment]
Everything is almost disconnected on the driver side. Just got to do the passenger side and a few things underneath and then I can raise the cab off of it


Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2016 at 4:34 PM, Brad Craft<grasen@ymail.com> wrote:   What about the free hookers?

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2016 at 4:33 PM, Christopher Bloom<notifications@github.com> wrote:   
Actually, now that I think about it: Events will need signup functionality, something I don't want to have junking up Posts.

**Comment by Grasen** [comment]
What about the free hookers?

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2016 at 4:33 PM, Christopher Bloom<notifications@github.com> wrote:   
Actually, now that I think about it: Events will need signup functionality, something I don't want to have junking up Posts.

**Comment by Grasen** [comment]
He's suggesting that there is free Coke and hookers for every website sign-up

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2016 at 4:30 PM, Christopher Bloom<notifications@github.com> wrote:   
@saedo, you're suggesting essentially that Event is rolled into Post. So our content types would be:
   
   - Post - now includes start/end date fields
   - Image (actually I'm changing this to Media as it will let us post both image and video)
   - Guide

**Comment by illepic** [comment]
I'm going to tank this idea. Keeping these as separate content types gives us flexibility and ease of interface.

**Comment by illepic** [comment]
Even though we're not doing this, we should rename Image to Media and allow video + image.
